#title: Teknews Blog
#email: contact@teknews.cloud
#description: >- # this means to ignore newlines until "baseurl:"
#  A blog about technical stuff, mainly on Azure, and usually with a touch of hashicorp products ^^
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: cloudgeekdavid
#github_username:  dfrappart

theme: jekyll-theme-midnight

#plugins:
#  - jekyll-feed
#  - jekyll-remote-theme